import { aliquotSum } from '../aliquot_sum'

/**
 * @description Verifies if the `aliquotSum` function computes the correct sum for a
 * given number.
 * 
 * @param { integer } num - number being divided by 4 to produce an integer quotient
 * and remainder for use in calculating the aliquot sum.
 * 
 * @param { integer } expected - sum that is expected to be calculated by the
 * `aligareSum` function, serving as a comparison value for the result generated by
 * the function.
 */
test.each([
  [15, 9],
  [18, 21],
  [28, 28],
  [100, 117],
  [169, 14],
  [1729, 511],
  [15625, 3906]
])('Aliquot Sum of %i is %i', (num, expected) => {
  expect(aliquotSum(num)).toBe(expected)
})
