import { countingSort } from '../counting_sort'

const testCases = [
  [
    [3, 0, 2, 5, 4, 1],
    [0, 1, 2, 3, 4, 5]
  ],
  [
    [6, 4, 2, 1, 3, 5],
    [1, 2, 3, 4, 5, 6]
  ],
  [
    [11, 14, 12, 15, 16, 13],
    [11, 12, 13, 14, 15, 16]
  ],
  [
    [13, 18, 2, 15, 43, 11],
    [2, 11, 13, 15, 18, 43]
  ]
]

/**
 * @description Counts its inputs and returns their sorted range, excluding duplicates.
 * 
 * @param { ... according to its declared type signature in the code snippet provided.
 * } input - 1D array of integers that needs to be sorted.
 * 
 * 	* `Math.min ... input`: This expression computes the minimum value of all elements
 * in `input`.
 * 	* `Math.max ... input`: This expression computes the maximum value of all elements
 * in `input`.
 * 
 * @param { number } expected - expected output of the counting sort algorithm, which
 * is compared to the actual output generated by the function for proper operation verification.
 */
it.each(testCases)(
  'The countingSort of the array %p is %p',
  (input, expected) => {
    const res = countingSort(input, Math.min(...input), Math.max(...input))
    expect(res).toEqual(expected)
  }
)
